package common.entity.register;

import java.util.Date;

/**
 * TSymStaff generated by MyEclipse Persistence Tools
 */

public class TSymStaff implements java.io.Serializable,java.lang.Cloneable {

	@Override
	public TSymStaff clone() throws CloneNotSupportedException {
		return (TSymStaff)super.clone();
	}


	/**
	 * 
	 */
	private static final long serialVersionUID = 8209681325014723465L;

	private String staffId;

	private String staffCode;

	private String staffName;

	private Long orgId;

	private String sex;

	private String photo;

	private String email;

	private String mobile;

	private String phone;

	private String address;

	private String zip;

	private String certType;

	private String certNbr;

	private Date effDate;

	private Date expDate;

	private String password;
	
	private String pwd;
	
	private String clPwd;

	public String getClPwd() {
		return clPwd;
	}

	public void setClPwd(String clPwd) {
		this.clPwd = clPwd;
	}

	public String getPwd() {
		return pwd;
	}

	public void setPwd(String pwd) {
		this.pwd = pwd;
	}


	private String pwdStat;

	private String pwdCtrl;

	private Date pwdNewtime;

	private Long pwdValidday;

	private Long pwdErrtimes;

	private Long pwdTrytimes;

	private String memo;

	private String stat;
	
	private String extFlag;
	
	//������������ֶ��޹� 
	private String contactMan;  //jϵ��

	//֧������
	private String payPwd;
	
	//��ɫ
	private Long roleId;
	private boolean sunListFlag = false;
	
	//��ɫ����
	private Long roleSeq;
	//�����
	private String partnerOrgName;
	
	//��ҵ���
	private String partnerName;
	
	private String custId;
	private String prtnId;
	//��ʶ�Ƿ�ӻ����ҵ����Ա������в���(��/true,��/false)
	private String isCum;
	
	// Constructors

	public String getIsCum() {
		return isCum;
	}

	public void setIsCum(String isCum) {
		this.isCum = isCum;
	}

	/** default constructor */
	public TSymStaff() {
	}

	/** minimal constructor */
	public TSymStaff(String staffCode, String staffName, Long orgId,
			String pwdStat, String pwdCtrl, String stat) {
		this.staffCode = staffCode;
		this.staffName = staffName;
		this.orgId = orgId;
		this.pwdStat = pwdStat;
		this.pwdCtrl = pwdCtrl;
		this.stat = stat;
	}

	/** full constructor */
	public TSymStaff(String staffCode, String staffName, Long orgId,
			String sex, String photo, String email, String mobile,
			String phone, String address, String zip, String certType,
			String certNbr, Date effDate, Date expDate, String password,
			String pwdStat, String pwdCtrl, Date pwdNewtime, Long pwdValidday,
			Long pwdErrtimes, Long pwdTrytimes, String memo, String stat) {
		this.staffCode = staffCode;
		this.staffName = staffName;
		this.orgId = orgId;
		this.sex = sex;
		this.photo = photo;
		this.email = email;
		this.mobile = mobile;
		this.phone = phone;
		this.address = address;
		this.zip = zip;
		this.certType = certType;
		this.certNbr = certNbr;
		this.effDate = effDate;
		this.expDate = expDate;
		this.password = password;
		this.pwdStat = pwdStat;
		this.pwdCtrl = pwdCtrl;
		this.pwdNewtime = pwdNewtime;
		this.pwdValidday = pwdValidday;
		this.pwdErrtimes = pwdErrtimes;
		this.pwdTrytimes = pwdTrytimes;
		this.memo = memo;
		this.stat = stat;
	}

	// Property accessors

	public String getContactMan() {
		return contactMan;
	}

	public void setContactMan(String contactMan) {
		this.contactMan = contactMan;
	}

	public String getStaffId() {
		return this.staffId;
	}

	public void setStaffId(String staffId) {
		this.staffId = staffId;
	}

	public String getStaffCode() {
		return this.staffCode;
	}

	public void setStaffCode(String staffCode) {
		this.staffCode = staffCode;
	}

	public String getStaffName() {
		return this.staffName;
	}

	public void setStaffName(String staffName) {
		this.staffName = staffName;
	}

	public Long getOrgId() {
		return this.orgId;
	}

	public void setOrgId(Long orgId) {
		this.orgId = orgId;
	}

	public String getSex() {
		return this.sex;
	}

	public void setSex(String sex) {
		this.sex = sex;
	}

	public String getPhoto() {
		return this.photo;
	}

	public void setPhoto(String photo) {
		this.photo = photo;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getZip() {
		return this.zip;
	}

	public void setZip(String zip) {
		this.zip = zip;
	}

	public String getCertType() {
		return this.certType;
	}

	public void setCertType(String certType) {
		this.certType = certType;
	}

	public String getCertNbr() {
		return this.certNbr;
	}

	public void setCertNbr(String certNbr) {
		this.certNbr = certNbr;
	}

	public Date getEffDate() {
		return this.effDate;
	}

	public void setEffDate(Date effDate) {
		this.effDate = effDate;
	}

	public Date getExpDate() {
		return this.expDate;
	}

	public void setExpDate(Date expDate) {
		this.expDate = expDate;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getPwdStat() {
		return this.pwdStat;
	}

	public void setPwdStat(String pwdStat) {
		this.pwdStat = pwdStat;
	}

	public String getPwdCtrl() {
		return this.pwdCtrl;
	}

	public void setPwdCtrl(String pwdCtrl) {
		this.pwdCtrl = pwdCtrl;
	}

	public Date getPwdNewtime() {
		return this.pwdNewtime;
	}

	public void setPwdNewtime(Date pwdNewtime) {
		this.pwdNewtime = pwdNewtime;
	}

	public Long getPwdValidday() {
		return this.pwdValidday;
	}

	public void setPwdValidday(Long pwdValidday) {
		this.pwdValidday = pwdValidday;
	}

	public Long getPwdErrtimes() {
		return this.pwdErrtimes;
	}

	public void setPwdErrtimes(Long pwdErrtimes) {
		this.pwdErrtimes = pwdErrtimes;
	}

	public Long getPwdTrytimes() {
		return this.pwdTrytimes;
	}

	public void setPwdTrytimes(Long pwdTrytimes) {
		this.pwdTrytimes = pwdTrytimes;
	}

	public String getMemo() {
		return this.memo;
	}

	public void setMemo(String memo) {
		this.memo = memo;
	}

	public String getStat() {
		return this.stat;
	}

	public void setStat(String stat) {
		this.stat = stat;
	}

	public String getPayPwd() {
		return payPwd;
	}

	public void setPayPwd(String payPwd) {
		this.payPwd = payPwd;
	}

	public Long getRoleId() {
		return roleId;
	}

	public void setRoleId(Long roleId) {
		this.roleId = roleId;
	}

	public boolean isSunListFlag() {
		return sunListFlag;
	}

	public void setSunListFlag(boolean sunListFlag) {
		this.sunListFlag = sunListFlag;
	}

	public String getPartnerOrgName() {
		return partnerOrgName;
	}

	public void setPartnerOrgName(String partnerOrgName) {
		this.partnerOrgName = partnerOrgName;
	}

	public String getPartnerName() {
		return partnerName;
	}

	public void setPartnerName(String partnerName) {
		this.partnerName = partnerName;
	}

	public String getCustId() {
		return custId;
	}

	public void setCustId(String custId) {
		this.custId = custId;
	}

	public String getPrtnId() {
		return prtnId;
	}

	public void setPrtnId(String prtnId) {
		this.prtnId = prtnId;
	}

	public String getExtFlag() {
		return extFlag;
	}

	public void setExtFlag(String extFlag) {
		this.extFlag = extFlag;
	}

	public Long getRoleSeq() {
		return roleSeq;
	}

	public void setRoleSeq(Long roleSeq) {
		this.roleSeq = roleSeq;
	}

}