package common.entity.bank;

/**
 * TBankParam generated by MyEclipse Persistence Tools
 */

public class TBankParam implements java.io.Serializable {

	// Fields

	private Integer paramId;

	private TBankInfo TBankInfo;

	private String paramType;

	private String paramName;

	private String paramDesc;

	private String paramValue;

	private String paramLimit;

	private Integer showSeq;

	private String submit;

	private String editable;

	// Constructors

	/** default constructor */
	public TBankParam() {
	}

	/** minimal constructor */
	public TBankParam(TBankInfo TBankInfo) {
		this.TBankInfo = TBankInfo;
	}

	/** full constructor */
	public TBankParam(TBankInfo TBankInfo, String paramType, String paramName,
			String paramDesc, String paramValue, String paramLimit,
			Integer showSeq, String submit, String editable) {
		this.TBankInfo = TBankInfo;
		this.paramType = paramType;
		this.paramName = paramName;
		this.paramDesc = paramDesc;
		this.paramValue = paramValue;
		this.paramLimit = paramLimit;
		this.showSeq = showSeq;
		this.submit = submit;
		this.editable = editable;
	}

	// Property accessors

	public Integer getParamId() {
		return this.paramId;
	}

	public void setParamId(Integer paramId) {
		this.paramId = paramId;
	}

	public TBankInfo getTBankInfo() {
		return this.TBankInfo;
	}

	public void setTBankInfo(TBankInfo TBankInfo) {
		this.TBankInfo = TBankInfo;
	}

	public String getParamType() {
		return this.paramType;
	}

	public void setParamType(String paramType) {
		this.paramType = paramType;
	}

	public String getParamName() {
		return this.paramName;
	}

	public void setParamName(String paramName) {
		this.paramName = paramName;
	}

	public String getParamDesc() {
		return this.paramDesc;
	}

	public void setParamDesc(String paramDesc) {
		this.paramDesc = paramDesc;
	}

	public String getParamValue() {
		return this.paramValue;
	}

	public void setParamValue(String paramValue) {
		this.paramValue = paramValue;
	}

	public String getParamLimit() {
		return this.paramLimit;
	}

	public void setParamLimit(String paramLimit) {
		this.paramLimit = paramLimit;
	}

	public Integer getShowSeq() {
		return this.showSeq;
	}

	public void setShowSeq(Integer showSeq) {
		this.showSeq = showSeq;
	}

	public String getSubmit() {
		return this.submit;
	}

	public void setSubmit(String submit) {
		this.submit = submit;
	}

	public String getEditable() {
		return this.editable;
	}

	public void setEditable(String editable) {
		this.editable = editable;
	}

}