package common.entity.bank;

import java.util.HashSet;
import java.util.Set;

/**
 * TBankInfo generated by MyEclipse Persistence Tools
 */

public class TBankInfo implements java.io.Serializable {

	// Fields

	private Integer bankId;

	private String bankCode;

	private String bankName;

	private Integer orderidLen;

	private String intfName;

	private String intfVer;

	private String intfType;

	private String certFile;

	private String certFileTax;

	private String certFileBank;

	private String keyFile;

	private String keyFileTax;

	private String keyPass;

	private String keyPassTax;

	private String logoFile;

	private String status;

	private String bankType;

	private Set TBankParams = new HashSet(0);

	// Constructors

	/** default constructor */
	public TBankInfo() {
	}

	/** minimal constructor */
	public TBankInfo(String bankCode) {
		this.bankCode = bankCode;
	}

	/** full constructor */
	public TBankInfo(String bankCode, String bankName, Integer orderidLen,
			String intfName, String intfVer, String intfType, String certFile,
			String certFileTax, String certFileBank, String keyFile,
			String keyFileTax, String keyPass, String keyPassTax,
			String logoFile, String status, String bankType, Set TBankParams) {
		this.bankCode = bankCode;
		this.bankName = bankName;
		this.orderidLen = orderidLen;
		this.intfName = intfName;
		this.intfVer = intfVer;
		this.intfType = intfType;
		this.certFile = certFile;
		this.certFileTax = certFileTax;
		this.certFileBank = certFileBank;
		this.keyFile = keyFile;
		this.keyFileTax = keyFileTax;
		this.keyPass = keyPass;
		this.keyPassTax = keyPassTax;
		this.logoFile = logoFile;
		this.status = status;
		this.bankType = bankType;
		this.TBankParams = TBankParams;
	}

	// Property accessors

	public Integer getBankId() {
		return this.bankId;
	}

	public void setBankId(Integer bankId) {
		this.bankId = bankId;
	}

	public String getBankCode() {
		return this.bankCode;
	}

	public void setBankCode(String bankCode) {
		this.bankCode = bankCode;
	}

	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public Integer getOrderidLen() {
		return this.orderidLen;
	}

	public void setOrderidLen(Integer orderidLen) {
		this.orderidLen = orderidLen;
	}

	public String getIntfName() {
		return this.intfName;
	}

	public void setIntfName(String intfName) {
		this.intfName = intfName;
	}

	public String getIntfVer() {
		return this.intfVer;
	}

	public void setIntfVer(String intfVer) {
		this.intfVer = intfVer;
	}

	public String getIntfType() {
		return this.intfType;
	}

	public void setIntfType(String intfType) {
		this.intfType = intfType;
	}

	public String getCertFile() {
		return this.certFile;
	}

	public void setCertFile(String certFile) {
		this.certFile = certFile;
	}

	public String getCertFileTax() {
		return this.certFileTax;
	}

	public void setCertFileTax(String certFileTax) {
		this.certFileTax = certFileTax;
	}

	public String getCertFileBank() {
		return this.certFileBank;
	}

	public void setCertFileBank(String certFileBank) {
		this.certFileBank = certFileBank;
	}

	public String getKeyFile() {
		return this.keyFile;
	}

	public void setKeyFile(String keyFile) {
		this.keyFile = keyFile;
	}

	public String getKeyFileTax() {
		return this.keyFileTax;
	}

	public void setKeyFileTax(String keyFileTax) {
		this.keyFileTax = keyFileTax;
	}

	public String getKeyPass() {
		return this.keyPass;
	}

	public void setKeyPass(String keyPass) {
		this.keyPass = keyPass;
	}

	public String getKeyPassTax() {
		return this.keyPassTax;
	}

	public void setKeyPassTax(String keyPassTax) {
		this.keyPassTax = keyPassTax;
	}

	public String getLogoFile() {
		return this.logoFile;
	}

	public void setLogoFile(String logoFile) {
		this.logoFile = logoFile;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getBankType() {
		return this.bankType;
	}

	public void setBankType(String bankType) {
		this.bankType = bankType;
	}

	public Set getTBankParams() {
		return this.TBankParams;
	}

	public void setTBankParams(Set TBankParams) {
		this.TBankParams = TBankParams;
	}

}